; Main test library

(test
 (name test_x11)
 (action
  (run %{test} --show-errors))
 (modules test_x11)
 (libraries
  alcotest
  test_xwindowattributes
  test_xevent
  test_x
  test_compilation))

; XEvent conversion tests

(library
 (name test_xwindowattributes)
 (modules test_xwindowattributes)
 (foreign_stubs
  (language c)
  (names test_xwindowattributes))
 (libraries x11 alcotest))

(library
 (name test_xevent)
 (modules test_xevent)
 (foreign_stubs
  (language c)
  (names test_xevent))
 (libraries x11 alcotest))

(library
 (name test_x)
 (modules test_x)
 (libraries x11 alcotest))

(library
 (name test_compilation)
 (modules test_compilation)
 (libraries x11 alcotest))

(rule
 (with-stdout-to
  test_xevent.c.formatted
  (run clang-format %{dep:test_xevent.c})))

(rule
 (alias fmt)
 (action
  (diff test_xevent.c test_xevent.c.formatted)))
