(library
 (public_name x11)
 (name x11)
 (libraries ctypes ctypes.stubs)
 (foreign_stubs
  (language c)
  (names xevent xwindowattributes x))
 (c_library_flags (-lX11))
 (ctypes
  (external_library_name x11)
  (headers
   (include "X11/X.h" "X11/Xlib.h"))
  (type_description
   (instance Types)
   (functor type_description))
  (function_description
   (instance Functions)
   (functor function_description))
  (generated_entry_point C)))

(rule
 (with-stdout-to
  xevent.c.formatted
  (run clang-format %{dep:xevent.c})))

(rule
 (with-stdout-to
  xwindowattributes.c.formatted
  (run clang-format %{dep:xwindowattributes.c})))

(rule
 (with-stdout-to
  x.c.formatted
  (run clang-format %{dep:x.c})))

(rule
 (alias fmt)
 (action
  (progn
   (diff xwindowattributes.c xwindowattributes.c.formatted)
   (diff xevent.c xevent.c.formatted)
   (diff x.c x.c.formatted))))
