(library
 (public_name x11)
 (name x11)
 (foreign_stubs
  (language c)
  (names xevent x))
 (c_library_flags (-lX11)))

(rule
 (with-stdout-to
  xevent.c.formatted
  (run clang-format %{dep:xevent.c})))

(rule
 (with-stdout-to
  x.c.formatted
  (run clang-format %{dep:x.c})))

(rule
 (alias fmt)
 (action
  (progn
   (diff xevent.c xevent.c.formatted)
   (diff x.c x.c.formatted))))
